server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/dfdz_realty?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
#  mapper-locations: classpath:mapping/*Mapper.xml
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.app.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug